In [18]:
import numpy as np

task 1

In [6]:
a = np.array([[1, 2, 3, 3, 1],
              [6, 8, 11, 10, 7]])
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [17]:
mean_a = np.array([a[0:6, 0].mean(), (a[0:6, 1].mean())])
mean_a

array([2. , 8.4])

task 2

In [19]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

task 3

In [33]:
x = a_centered[:, 0]
y = a_centered[:, 1]
a_centered_sp = np.dot(x, y)
a_centered_sp = a_centered_sp / (a.shape[0] - 1)
a_centered_sp

2.0

task 4

In [1]:
a_centered_sp = np.cov(a.transpose())[0, 1]
a_centered_sp

NameError: name 'np' is not defined

In [ ]:
###