In [2]:
import numpy as np

In [3]:
a = [i for i in range(10)]

In [4]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
b = np.array(a)

In [6]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
b = np.array([i for i in range(10)])

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = np.array(a, dtype = float)

In [10]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
b = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
            [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [12]:
b.shape


(3, 10)

In [13]:
b.size

30

In [14]:
b[0][0]

0

In [15]:
b[1, 1]

11

In [16]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [17]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [18]:
c = b[1:, 5:]

In [19]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [22]:
c = b[1:, 5:].copy()

In [23]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [25]:
b[1, 5] = 898

In [26]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 898,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]])

In [27]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])


#### vector operations


In [30]:
a = np.array([0, 1, 2, 3, 4])

In [31]:
b = np.array([5, 6, 7, 8, 9])

In [33]:
c = a + b
c = np.add(a, b)

In [34]:
c

array([ 5,  7,  9, 11, 13])

In [37]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [40]:
d = a - b
d = np.subtract(a, b)

In [41]:
d

array([ 2, -1,  1,  3,  0])

In [43]:
sp = a @ b

In [44]:
sp

104

# Matrixes operations

In [51]:
a = np.array([[0, 1], 
              [2, 3], 
              [4, 5]])
b = np.array([[6, 7], 
              [8, 9]])

In [52]:
c = np.dot(a, b)
c

array([[ 8,  9],
       [36, 41],
       [64, 73]])

In [67]:
a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
a_square = np.linalg.matrix_power(a, 2)
a_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [65]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [68]:
np.dot(i, a)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [69]:
a = np.array([[0, 1], 
              [2, 3], 
              [4, 5]])

In [70]:
at = a.transpose()
at

array([[0, 2, 4],
       [1, 3, 5]])

In [71]:
b = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [72]:
b_inv = np.linalg.inv(b)
b_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [73]:
b_inv = np.linalg.inv(b_inv)
b_inv

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

# Lists

In [75]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
b= np.ones((5, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [86]:
 b = np.random.randint(0, 10)

In [87]:
np.random.choice(b)

3

In [89]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
b = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])